yast/yast-iscsi-client

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb

This bug-fix solves the initial problem in bsc#981693 that an error popup blocks AutoYaST when trying to login to target twice.
The workaround is to delete the <iscsi-client> section from the xml-profile. The installation was successful then but hanged (still not solved) during network config. 
With the bug-fix the xml-profile generated with clone_system can be used.

don't block AutoYaST install (bsc#981693)

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb
test/getiBFT_spec.rb

If iface.initiatorname is unset (as is usually the case, it seems) - replace
with value from /etc/iscsi/initiatorname.iscsi.

fix comparing iscsi node data (bsc#1119698)

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb

https://bugzilla.suse.com/show_bug.cgi?id=1131049
When configuring iSCSI YaST runs into a timeout waiting for `iscsiadm` to succeed at several places. As it happens, `iscsiadm` may return 21 to indicate success.
https://trello.com/c/m4bAAjig
See the long discussion in [bsc#1131049](https://bugzilla.suse.com/show_bug.cgi?id=1131049) for details. In essence, simply accept that `iscsiadm` may exit with 21 to mean success.
Closed older PR: https://github.com/yast/yast-iscsi-client/pull/82

iscsiadm may have exit code 21 on success (bsc#1131049)

---

.gitignore
package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb
test/iscsi_client_lib_test.rb
test/test_helper.rb

---
This PR fix a typo checking the status of `iscsid.socket` which forces to always stop the service and start the socket.
It was reported and fixed for SLE-15 [(bsc#1103681)](https://bugzilla.suse.com/show_bug.cgi?id=1103681) and now is requested  [(bsc#1157349)](https://bugzilla.novell.com/show_bug.cgi?id=1157349#c16) to backport the fix also for SLE-12-SP4/5

[Backport]  Fix typo in #getServiceStatus (bsc#1103681 and bsc#1157349)

---

.gitignore
package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb
test/iscsi_client_lib_test.rb
test/test_helper.rb

> 
> This PR fix a typo checking the status of `iscsid.socket` which forces to always stop the service and start the socket.
> 
> It was reported and fixed for SLE-15 [(bsc#1103681)](https://bugzilla.suse.com/show_bug.cgi?id=1103681) and now is requested  [(bsc#1157349)](https://bugzilla.novell.com/show_bug.cgi?id=1157349#c16) to backport the fix also for SLE-12-SP4/5

[SLE-12-SP5]  Fix typo in #getServiceStatus (bsc#1103681 and bsc#1157349)

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/include/iscsi-client/dialogs.rb

Recently and as consequence of this [PR](https://github.com/yast/yast-yast2/pull/999) we have changed the default service action after writing the configuration. 
In the case of the iscsi-client, the service should not be touched at all.
- https://bugzilla.novell.com/show_bug.cgi?id=1160374
Propose `:nothing` as the default_action for the service widget.

Service default action

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb
test/iscsi_client_lib_test.rb

backport of https://github.com/yast/yast-iscsi-client/pull/90 no other branches are affected as bug is caused by shell escaping done in SP1.

Backport discovery fix

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/include/iscsi-client/dialogs.rb

The behavior of the service widget was changed for SLE-15-SP2 (and Tumbleweed) in https://github.com/yast/yast-yast2/pull/999
That broke yast-iscsi-client, which was fixed (also for SLE-15-SP2 and TW) via https://github.com/yast/yast-iscsi-client/pull/89
But afterwards, the new behavior of the widget was backported to SLE-15-SP1. See https://github.com/yast/yast-yast2/pull/1001
As a consequence, the yast-iscsi-client fix from #89 also needs to be backported to SLE-15-SP1 (reported as [bsc#1162078](https://bugzilla.suse.com/show_bug.cgi?id=1162078)). That's exactly what the current pull request is about. Check the original pull request for details about what is changed and why.

Backport of Knut changes in 4.2.3 to fix bsc#1160374

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClient.rb

An openQA test is failing because the iscsid.socket is expected to be running after restarting it but it is not.
It seems that the option for restarting the socket is not selected in the test and thus, the service is started instead of the socket, but, if selected correctly, there are situations where the socket is not started because the service was already running.
- https://trello.com/c/dpNmTxj4/1637-5-sles15-sp1-sp2-p5-1160606-build-1221-iscsidsocket-is-inactive-when-configure-target-with-yast-iscsi-client
- https://bugzilla.suse.com/show_bug.cgi?id=1160606#c15
After some tests and checks, it seems that the iscsi service should be handled at the end of the **CompoundService** as it is done by getServiceStatus.
https://github.com/yast/yast-iscsi-client/blob/d2349fd00a05424fab73690b79f7c …

Change services order

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/include/iscsi-client/helps.rb

When connecting to an iSCSI target using iBFT, the start-up mode is irrelevant and, as consequence, it was decided a long time ago that YaST should display the corresponding widget as blocked with the value "onboot". See all the details here: https://bugzilla.suse.com/show_bug.cgi?id=954509
But that intentional behavior was reported recently as [bug#1170317](https://bugzilla.suse.com/show_bug.cgi?id=1170317). As using an iBFT device for non-booting purposes is admittedly a corner case and finding a best solution is not easy (the mount point is unknown when the device is configured), it was decided to just improve the help text to mitigate the situation.
|  result in text mode | result in Qt |
|---|---|
| ![help-ncurses](https://user-images.githubusercontent.com/3638289/82456900-19c01c00-9a …

Explain why Startup combobox is disabled

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/include/iscsi-client/helps.rb

As a fix (or mitigation, to be more precise) for [bug#1170317](https://bugzilla.suse.com/show_bug.cgi?id=1170317), an extension of the help text was implemented for the master branch at #100 (see that pull request for details and screenshots).
But @jsrain asked us in the mentioned  [bug#1170317](https://bugzilla.suse.com/show_bug.cgi?id=1170317) to submit that new text to SLE-15-SP2 as well. This pull request cherry-picks the changes from #100 to incorporate them in the SLE-15-SP2 branch.

Cherry pick of #100: Explain why Startup combobox is disabled

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/autoyast-rnc/iscsi-client.rnc

Add the 'iface' element to the AutoYaST schema. According to [this piece of code](https://github.com/yast/yast-iscsi-client/blob/674e0cf58c8bf769b27e343125973c9fa3c03a7d/src/include/iscsi-client/widgets.rb#L894-L914), it was the only missing element.
Bug: [bsc#1182193](https://bugzilla.suse.com/show_bug.cgi?id=1182193)
Trello: https://trello.com/c/QGvizs7U/

Add iface element

---

package/yast2-iscsi-client.spec

Now that the tests are actually being executed in OBS (see #106), we need `yast2-packager` as a build time dependency.

Add yast2-packager build runtime dependency

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb

Adds qede/qedi offload-card support to yast2-iscsi-client.
Needs to go into SLE-12-SP5 as well?

Add iscsi support for qedi/qede offload cards.

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/include/iscsi-client/dialogs.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1195226
Ruby 3.0 has slightly changed the method argument handling.
- https://ruby-doc.org/core-3.0.0/NEWS_md.html

adjust to ruby 3.0 (bsc#1195226)

---

src/clients/iscsi-client_finish.rb
src/modules/IscsiClient.rb
src/modules/IscsiClientLib.rb
test/iscsi-client_finish_test.rb
test/iscsi_client_lib_test.rb
test/iscsi_client_test.rb

According to [bsc#1194432](https://bugzilla.suse.com/show_bug.cgi?id=1194432) YaST enables the `iscsiuio` daemon always when some iSCSI devices are configured. But `iscsiuio` is the userspace offloading daemon for QLogic (formerly Broadcom) devices, so it's only needed when hardware offloading is configured for a device using the `bnx2i` or `qedi` drivers. In any other case, enabling `iscsiuio` only makes the boot process slower with no gain.
On the other hand, the convoluted code of yast-iscsi-client makes very hard to understand and modify the management of services.
This pull request includes a couple of preliminary cleanup commits that should not change how the module behave. Instead, those commits provide small code cleanups and a lot of inline documentation to help to understand how …

Start iscsiuio only in presence of the relevant hardware (bsc#1194432)

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec

As part of an [effort to make easier to contribute](https://trello.com/c/eWOWDp1I/2915-5-iscsi-client-lower-the-bar) to this module (specially for @gonzoleeman but not only for him), we created these two pull requests:
- https://github.com/yast/yast-iscsi-client/pull/115
- https://github.com/yast/yast-iscsi-client/pull/116
But we didn't increase the version of the package during the process. That implies our continuous integration system will not auto-submit the changes to openSUSE Tumbleweed.
Increase the version, so the package is submitted to Tumbleweed and we can get some feedback about the new `iscsiuio` handling and/or detect if something breaks with all the introduced changes (the mentioned pull requests include quite some code cleanup).

Version bump and changelog

---

.rubocop.yml
package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/include/iscsi-client/widgets.rb
src/modules/IscsiClientLib.rb

When executing the module in a container, the discovery and connection of targets only worked if the kernel module `iscsi_tcp` was loaded in the host system. The command `iscsiadm` traditionally took care of loading that module if needed in a way that was transparent to YaST. But that mechanism does not work when YaST (and, thus, the `iscsiadm` command) is executed in a container.
Additionally, when diagnosing the problem it was found that the command `iscsiadm` was executed using the agent `.background` which is deprecated and left a lot of errors like this in the YaST logs:
```
WARNING: .background agent is obsoleted, use .process agent instead!
```
- First of all, the method using the `.background` agent was documented and manually tested, since it exhibited a [pretty inconsistent and …

Make it work in containers and stop using deprecated agent

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/lib/y2iscsi_client/timeout_process.rb
src/modules/IscsiClientLib.rb

https://bugzilla.suse.com/show_bug.cgi?id=1204959
https://trello.com/c/sJaVnYvE/
An external command `/usr/sbin/iscsiadm` could not be called, so probing for iSCSI hardware failed, so the whole module became unusable.
During the _usr-merge_, many commands were moved from `/sbin` to `/usr/sbin` (and from `/bin` to `/usr/bin`), and we already did the migration in _master_ so _factory_ complied to the new standard.
But that meant that SLE-15 SP5, which inherits all YaST code from _master_, now failed with those external commands: Unlike _factory_, SLE-15 SPx does _not_ have any compatibility symlinks between `/sbin` and `/usr/sbin` (or `/bin` and `/usr/bin`), resulting in this _command not found_ error.
As already discussed half a year ago, our new policy is to not use an absolute path for …

Call External Commands Without Path

---

package/yast2-iscsi-client.changes
src/include/iscsi-client/widgets.rb
src/lib/y2iscsi_client/authentication.rb
src/lib/y2iscsi_client/config.rb
src/lib/y2iscsi_client/timeout_process.rb
src/modules/IscsiClientLib.rb
test/iscsi_client_lib_test.rb
test/y2iscsi_client/timeout_process_test.rb

Responsibilities are not properly distributed in the yast-iscsi-client code.
- The UI takes care of things that should be done by `IscsiClientLib` (eg. discovering iSCSI nodes or deleting nodes from the database).
- `IscsiClientLib` often communicate directly with the user via pop-up messages.
- The logic to deal with CHAP authentication is spread all over the code and repeated over and over.
That makes impossible to write new code that relies on `IscsiClientLib` to offer a new interface for iSCSI configuration. And that's exactly what we want to do in D-Installer.
Do the minimal changes in the code to allow all the basic operations to be performed relying only on `IscsiClientLib`  in a way it's independent from the YaST UI. That consist on two facets:
- Extended `IscsiClientLib` with new …

Refactoring needed for D-Installer

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClient.rb

_**This is for SLE-15-SP5**_. Merge PRs to SLE-15-SP5 and _master_ will follow.
https://trello.com/c/UoVA6ohy/
https://bugzilla.suse.com/show_bug.cgi?id=1214273
"YaST iSCSI initiator setup failing on startup"
_Notice that the repo / package name for this is `yast-iscsi-client`._
Crash when starting the _YaST iSCSI initiator_ (YaST iSCSI client) module.
No _iscsiuio_ systemd service running, so it couldn't be detected. The service was not running because the corresponding `iscsiuio` driver package was not installed, even though it was determined that it would have been needed for that setup.
The root cause was that there were many (too many) exceptions when those support packages were not installed, and that customer had hit one of those cases.
This was initially an L3, but the L3 team …

Add Support Packages on Demand [SLE-15-SP5]

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClient.rb

_**This the merge of PR #125 into SLE-15-SP6**_. 
https://trello.com/c/UoVA6ohy/
https://bugzilla.suse.com/show_bug.cgi?id=1214273
"YaST iSCSI initiator setup failing on startup"
_Notice that the repo / package name for this is `yast-iscsi-client`._
Crash when starting the _YaST iSCSI initiator_ (YaST iSCSI client) module.
No _iscsiuio_ systemd service running, so it couldn't be detected. The service was not running because the corresponding `iscsiuio` driver package was not installed, even though it was determined that it would have been needed for that setup.
The root cause was that there were many (too many) exceptions when those support packages were not installed, and that customer had hit one of those cases.
This was initially an L3, but the L3 team advised the customer how to add …

Add Support Packages on Demand [SLE-15-SP6]

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClient.rb

_**This the merge of PR #126 / #125 into master**_. 
https://trello.com/c/UoVA6ohy/
https://bugzilla.suse.com/show_bug.cgi?id=1214273
"YaST iSCSI initiator setup failing on startup"
_Notice that the repo / package name for this is `yast-iscsi-client`._
Crash when starting the _YaST iSCSI initiator_ (YaST iSCSI client) module.
No _iscsiuio_ systemd service running, so it couldn't be detected. The service was not running because the corresponding `iscsiuio` driver package was not installed, even though it was determined that it would have been needed for that setup.
The root cause was that there were many (too many) exceptions when those support packages were not installed, and that customer had hit one of those cases.
This was initially an L3, but the L3 team advised the customer how to …

Add Support Packages on Demand [master]

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb

https://bugzilla.suse.com/show_bug.cgi?id=1225432
Passwords may be leaked to the log
When the configuration is written to file, it is also logged completely to the y2log. This includes any passwords that the user entered when configuring iSCSI.
Unfortunately, the config class is just a very thin wrapper around an array of hashes, not a real class with dedicated fields, so we cannot use the `secret_attr` method that we use in other places.
Don't log the complete configuration, only the fact that is was written.
The log format is unwieldy and very hard to read for a human anyway, so it's not very useful to log it in the first place.

Prevent Leaking Passwords to the Log

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb

This is the backport to _SLE-15-SP6_ of #129 and #128.
https://bugzilla.suse.com/show_bug.cgi?id=1225432
Passwords may be leaked to the log.
When the configuration is written to file, it is also logged completely to the y2log. This includes any passwords that the user entered when configuring iSCSI.
Unfortunately, the config class is just a very thin wrapper around an array of hashes, not a real class with dedicated fields, so we cannot use the `secret_attr` method that we use in other places.
Don't log the complete configuration, only the fact that is was written.
The log format is unwieldy and very hard to read for a human anyway, so it's not very useful to log it in the first place.
- Original PR for _master_: #128 
- Merge to SLE-15-SP5: #129

Prevent Leaking Passwords to the Log [SLE-15-SP6]

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/clients/inst_iscsi-client.rb
src/lib/y2iscsi_client/finish_client.rb
src/modules/IscsiClientLib.rb
test/iscsi_client_lib_test.rb
test/mocking.rb
test/y2iscsi_client/finish_client_test.rb

When the iSCSI client is called during installation, it tries to do an auto login. This auto login call will add the nodes configurations provided by iBFT in case of present (iscsiadm -m discovery -t fw) but if the connected target tabs is not visited then the session is not read and the iscsi services are not activated at the end of the installation because the sessions are not populated properly.
It is not the only problem detected but also the discovery call is writing the nodes configuration persistently with the startup attribute as manual instead of onboot something that is not correct at all.
And last but not least the **iscsiuio.service** should be enabled independently of the socket one when it makes sense (offload supported / iBFT config).
- **Bug:** [bsc#1228084 …

Fix read of sessions when auto login and start iscsiuio.service instead of socket (bsc#1228084)

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/clients/inst_iscsi-client.rb
src/include/iscsi-client/dialogs.rb
src/include/iscsi-client/helps.rb
src/include/iscsi-client/widgets.rb
src/modules/IscsiClientLib.rb
test/data/chroot1/etc/iscsi/ifaces/bnx2i.ab:cd:de:fa:cf:29.ipv4.0
test/iscsi_client_lib_test.rb

Bugzilla: [bsc#1231385](https://bugzilla.suse.com/show_bug.cgi?id=1231385)
In the "iSCSI initiator" dialog, the offload card was not displayed correctly. Instead of bnx2i, the dialog showed "default (TCP)". I'm not sure what would have happened if I hadn't changed this to bnx2i.
In the "iBFT" dialog, the bnx2i transport was displayed correctly.
The selection of the offload card is relevant just in case we wanted to do some discover using that specific interface.
When a different offload card is selected it calls the iscsi_offload.sh script and select the related iscsi_iface to be used by discovery commands.
But the point is that the configuration is already done during in the initialization, so, doing it on selection doesn’t change anything at all.
What is even more important, the login …

Iscsi offload changes

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/clients/inst_iscsi-client.rb
src/include/iscsi-client/dialogs.rb
src/include/iscsi-client/helps.rb
src/include/iscsi-client/widgets.rb
src/modules/IscsiClientLib.rb
test/data/chroot1/etc/iscsi/ifaces/bnx2i.ab:cd:de:fa:cf:29.ipv4.0
test/iscsi_client_lib_test.rb

It merges #137 into master
Once we merge this request we should also adapt [agama](https://github.com/agama-project/agama)

Use iscsi ifaces instead of offload card (bsc#1231385) - master

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/include/iscsi-client/widgets.rb

It merges #139 into SLE-15-SP6
Fix for https://bugzilla.suse.com/show_bug.cgi?id=1233351

Fix typo when modifying the initiatorname (bsc#1233351) - SLE-15-SP7

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/include/iscsi-client/widgets.rb

It merges #140 into master.
Fix for https://bugzilla.suse.com/show_bug.cgi?id=1233351

Fix typo when modifying the initiatorname (bsc#1233351) - master

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb

In **aarch64** we are not getting the **iBFT** configuration because an arch condition which exclude it.
- [*bsc#1233802*](https://bugzilla.suse.com/show_bug.cgi?id=1233802)
Add arm and **aarch64** to the architectures supporting **iBFT** configuration.

Get iBFT configuration in case of ARM architecture (bsc#1233802)

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb

Although a qedi device is configured by firmware and autoLogon success it is not listed as a potential offload card because the feature is not present.
- https://bugzilla.suse.com/show_bug.cgi?id=1236433
Do not filter potential offload cards based on the iscsioffload feature but just based on the driver module and also check the transport name of the current iscsi files specially for qedi devices which could not have an associated network device obtained by hwinfo --netcard.

Fix the selection of potential offload cards (bsc#1236433)

---

package/yast2-iscsi-client.changes
package/yast2-iscsi-client.spec
src/modules/IscsiClientLib.rb

There are  iscsi offload cards that does not have an associated network interface and therefore cannot be used as a regular network card. We should not try to bring up network interfaces without a name.
- https://trello.com/c/4l7Ie4CS
- https://bugzilla.suse.com/show_bug.cgi?id=1246210
Skip unnamed interfaces from the list of network interfaces that need to be brought up.

No iface bring up
